# Generated by Django 4.1 on 2022-08-22 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("landing_pages", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="landingpageentry",
            name="name",
            field=models.CharField(blank=True, max_length=220),
        ),
    ]
