# Generated by Django 4.1 on 2022-08-22 16:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("landing_pages", "0002_alter_landingpageentry_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="landingpageentry",
            name="timestamp",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="landingpageentry",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
