# Generated by Django 4.1 on 2022-08-22 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("landing_pages", "0003_landingpageentry_timestamp_landingpageentry_updated"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="landingpageentry",
            name="updated",
        ),
    ]
