# Generated by Django 4.1 on 2022-08-22 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("landing_pages", "0005_landingpageentry_active"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="landingpageentry",
            name="active",
        ),
    ]
