# Generated by Django 4.1 on 2022-08-22 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("landing_pages", "0007_landingpageentry_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="landingpageentry",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
    ]
