# Generated by Django 4.1 on 2022-08-22 21:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("landing_pages", "0008_landingpageentry_notes"),
    ]

    operations = [
        migrations.AddField(
            model_name="landingpageentry",
            name="notes_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
